### ISSUE TITLE
I want to add these to the list

### ISSUE THREAD

**Issue by yceruto** [cuban-opensourcers/cuban-opensource#20]
**Django library for AJAX operations:**
https://github.com/yceruto/django-ajax

**Start point to build multiple Symfony applications with shared config, code and vendors in the same place/repo:**
https://github.com/yceruto/symfony-skeleton-vkernel

I'm also maintainer of https://github.com/EasyCorp/EasyAdminBundle but I guess it does not qualify here.

Saludos!

**Comment by glpzzz** [comment]
The first 2 are included. The last one, I'm not sure. We are trying to get original ideas. I let thisnopen for debate.
Nos vemos!!!

**Comment by n3omaster** [comment]
Si, sobre la segunda, el tema de Symfony con vendors, todavia recuerdo hace par de años como añoraba ese bundle completo.

Habría que hacer uno para laravel también. Hay muchos desposeídos con ganas de programar pero sin acceso a composer.

**Comment by Dps8** [comment]
Hello, I am from Cujae and we are working on several things. At this moment we are building a 3d printer with Arduino. The idea would be to develop a fimware that works with the components we use. The vast majority are recycled components from old printers. I still do not have specific things to upload. But I wanted to know if you can add this project to the list.

**Comment by glpzzz** [comment]
Hello! English o español que somos cubanos. En inglés pa Github que nos conviene. Socio, la idea es tener código fuente online para que sea accesible para todos. Una vez que tengan el repo creado, los ponemos en la lista. De echo, dame sus alias de Github para agregarlos a la organización. Nos vemos!!!

**Comment by etorresf** [comment]
Hello! I want add these software to the list:
https://github.com/etorresf/Nawito1906

**Comment by glpzzz** [comment]
Agregado

**Comment by etorresf** [comment]
Thanks for add Nawito to this list.


Quoting "Gabriel A. López López" <notifications@github.com>:
