### ISSUE TITLE
Add this full stack web framework, Raptor project

### ISSUE THREAD

**Issue by williamamed** [cuban-opensourcers/cuban-opensource#31]
This a opensource Project created in 2015, now we have a branch dedicated to Node.js  named Raptor.js 

https://github.com/williamamed/Raptor.js
https://www.npmjs.com/package/raptor-cli

**Comment by andaniel05** [comment]
Check the next guide for adds the project to the list.

https://github.com/cuban-opensourcers/cuban-opensource/blob/master/publish.md
