### ISSUE TITLE
Include projects

### ISSUE THREAD

**Issue by JoseVL92** [cuban-opensourcers/cuban-opensource#43]
Hi, is a pleasure to find this project and I want to be part of this.
I have three python libraries that I wanna share with cuban community (I'm a cuban guy living in Cuba, writing in English because... I don't know, repo description is in English).
These libraries are public in my profile, and URLs of each one are:
https://github.com/JoseVL92/http-requests
https://github.com/JoseVL92/sqlalchemy-connector
https://github.com/JoseVL92/text-miner

Descriptions are short, documentation is null, but they work and slowly I will document them better.

Greetings and thank you for this idea.

**Comment by JoseVL92** [comment]
Project http-requests even have a pypi package, you can download and install it with pip install http_requests

**Comment by glpzzz** [comment]
included
