### ISSUE TITLE
Is this only for projects developed in Cuba or by cuban developers

### ISSUE THREAD

**Issue by aleGuardiola** [cuban-opensourcers/cuban-opensource#69]
Hi, I am a cuban developer but I do not live in Cuba, I would like to post some of my open source projects here, is it possible?.

**Comment by glpzzz** [comment]
Totally!!!

On May 11, 2020 5:50:57 PM GMT-04:00, Alejandro Guardiola <notifications@github.com> wrote:
>Hi, I am a cuban developer but I do not live in Cuba, I would like to
>post some of my open source projects here, is it possible?.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cuban-opensourcers/cuban-opensource/issues/69

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aleGuardiola** [comment]
Ok, thanks
