### ISSUE TITLE
Is this for apps developed inside Cuba only?

### ISSUE THREAD

**Issue by codeadict** [cuban-opensourcers/cuban-opensource#8]
This is more a question than an issues, feel free to close after responding or leave open for others here. I personally have a few projects and libraries to share , some of them I developed while still living in Cuba, others outside but IMO they still count as Cuban developed software :).

**Comment by glpzzz** [comment]
And I assume you're Cuban...
Send your contributions!!!

**Comment by codeadict** [comment]
Yes, I'm Cuban. I'll send them soon. ✌️
